import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogOutBtn from "./LogOutBtn";
import Register from "./register/page";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <Head>
        <title>개놀자</title>
        <meta name="description" content="여행상품 next.js로 만들기"></meta>
        <meta name="keyword" content="로그인 만들기, 회원가입 만들기, DB 생성하기"></meta>
      </Head>
      <body className={inter.className}>
        <div className="top-logo">
          <Link href="/">
            <img src="/img/logo.png" alt="logo" />
          </Link>
        </div>

        <div className="g-menu">
          <ul>
            <li>
              <a href="/">Home</a>
            </li>
            <li>{session ? <LogOutBtn /> : <LoginBtn></LoginBtn>}</li>
            <li>
              <Link href="/register">Join</Link>
            </li>
            <li>
              <a href="/cart">Cart</a>
            </li>
            <li>
              <Link href="/notice">Notice</Link>
            </li>
          </ul>
        </div>
        <nav className="menu">
          <ul>
            <li>
              <Link href="/best10">BEST10</Link>
              <Link href="/hot">후기</Link>
              <Link href="/world">해외여행</Link>
              <Link href="/korea">국내여행</Link>
              <Link href="/port">항공</Link>
              <Link href="/hotel">Hotel</Link>
            </li>
            <li>
              <div>{/* <span>いらっしゃいませ {session.user.email}</span> */}</div>
            </li>
          </ul>
        </nav>

        {children}
        <footer className="footer">
          <div className="footer-inner">
            <ul>
              <li>
                <h4>NOTIFICATION</h4>
                <ul>
                  <li>
                    <Link href="/">회사소개</Link>
                  </li>
                  <li>
                    <Link href="/">이용약관</Link>
                  </li>
                  <li>
                    <Link href="/">이용안내</Link>
                  </li>
                  <li>
                    <Link href="/">개인정보 취급방침</Link>
                  </li>
                  <li>
                    <Link href="/">협찬/제휴문의</Link>
                  </li>
                </ul>
              </li>
              <li>
                <h4>COMPANY INFOMATION</h4>
                <ul>
                  <li>
                    <Link href="/">(주) 개놀자</Link>
                  </li>
                  <li>
                    <Link href="/">Address 서울 구로구 구로디지털단지 세운빌딩 9층 905호</Link>
                  </li>
                  <li>
                    <Link href="/">Owner 윤태욱</Link>
                  </li>
                  <li>
                    <Link href="/">General Director 조준영</Link>
                  </li>
                  <li>
                    <Link href="/">Business License .204-12-1111111</Link>
                  </li>
                  <li>
                    <Link href="/">Copyright &copy1 cho line All Right Reserved</Link>
                  </li>
                </ul>
              </li>
              <li>
                <h4>BANK ACCOUNT</h4>
                <p>무통장 입금안내</p>
                <ul>
                  <li>
                    <Link href="/">국민 11112123456</Link>
                  </li>
                  <li>
                    <Link href="/">농협 22222222</Link>
                  </li>
                  <li>
                    <Link href="/">신한 11113131313</Link>
                  </li>
                  <li>
                    <Link href="/">우리 4444444444</Link>
                  </li>
                  <li>
                    <Link href="/">기업 12341234</Link>
                  </li>
                </ul>
              </li>
              <li>
                <h4>CS CENTER</h4>
                <ul>
                  <li>
                    <Link href="/">Weekday AM 11:00 PM 8:00</Link>
                  </li>
                  <li>
                    <Link href="/">Lunch PM 13:00 - PM 14:00</Link>
                  </li>
                  <li>
                    <Link href="/">SAT/SUN/HOLIDAY.OFF</Link>
                  </li>
                  <li>
                    <Link href="/">CS Manager 윤채욱</Link>
                  </li>
                  <li>
                    <span>
                      전화량이 많아 게시판을 이용해주시면 <br /> 빠르게 답변을 들으실수 있습니다
                    </span>
                  </li>
                </ul>
                <p>1544-1544</p>
              </li>
            </ul>
          </div>
        </footer>
      </body>
    </html>
  );
}
